/* PlanetHell — catálogo do rolador.
   Paradas e regras conforme o Guia do Jogador (seções 5, 6, 7 e 8).
   a / p = atributo e perícia somados na parada. a2 = segundo atributo (quando não há perícia).
   dano = true quando o resultado vira dano contra um alvo.
   d = o que a rolagem é · dez = Despertar · col = Colapso · ftot = Fracasso total. */
window.PH_ROLAGENS = {
 ataque: { rot: 'Ataque', tipos: {
  desarmado: { n: 'Ataque desarmado', a: 'Força', p: 'Briga', dano: true, fisico: true, arma: 'desarmado',
   d: 'O defensor apara com Destreza + Briga, Armamento ou Atletismo. Dano superficial, dividido por dois antes de marcar.',
   dez: 'O golpe entra num ponto vital. Contra figurante, ele é incapacitado na hora, sem rolar dano.',
   col: 'Você se expôs: perdeu o equilíbrio, deixou a guarda aberta, acertou a parede em vez do alvo — e alguém viu.',
   ftot: 'O golpe passou raspando e o impulso levou você junto. Você está fora de posição.' },
  umamao: { n: 'Arma de uma mão', a: 'Destreza', p: 'Armamento', dano: true, fisico: true,
   d: 'Faca, cassetete, espada curta. O defensor apara ou esquiva.',
   dez: 'A lâmina encontra uma junta, um tendão, uma correia de equipamento. Escolha um efeito além do dano.',
   col: 'A arma prendeu, escapou da mão ou quebrou. Decida qual antes do próximo turno.',
   ftot: 'Você errou e ficou com o peso todo no pé errado.' },
  duasmaos: { n: 'Arma de duas mãos', a: 'Força', p: 'Armamento', dano: true, fisico: true,
   d: 'Machado, lança, marreta. Dano alto, guarda pior.',
   dez: 'O golpe atravessa a defesa e o que estava atrás dela. Portas e cobertura cedem junto.',
   col: 'O peso da arma levou você junto. Você está exposto até o fim do próximo turno.',
   ftot: 'Você acertou o chão, a parede ou o aliado errado.' },
  tiroteio: { n: 'Tiroteio (sob fogo)', a: 'Autocontrole', p: 'Armas de Fogo', dano: true, fisico: true,
   d: 'Troca de tiros sob pressão. O defensor usa Destreza + Atletismo.',
   dez: 'A posição do adversário deixa de existir: a cobertura cede, o tiro a atravessa, a arma dele trava.',
   col: 'A arma emperrou, o carregador acabou na pior hora, ou o tiro acertou o que não devia. Escolha.',
   ftot: 'Você gastou munição e revelou a sua posição.' },
  precisao: { n: 'Tiro de precisão', a: 'Perseverança', p: 'Armas de Fogo', dano: true, fisico: true,
   d: 'Alvo fixo, posição preparada. A manobra Mira soma +1 dado por turno gasto, até +3.',
   dez: 'Um tiro, um resultado. Você escolhe o que o tiro faz além do dano: desarma, imobiliza, corta uma comunicação, derruba a luz.',
   col: 'Você errou e o estampido entregou de onde veio. Alguém já vem na sua direção.',
   ftot: 'O tiro saiu e não acertou nada. A janela se fechou.' },
  saque: { n: 'Saque, cara a cara', a: 'Destreza', p: 'Armas de Fogo', dano: true, fisico: true,
   d: 'Quem atira primeiro. Sem mira, sem cobertura, sem segunda chance.',
   dez: 'Você atirou antes de o outro decidir atirar. Ele não responde neste turno.',
   col: 'Você sacou e a arma não estava pronta. O outro já está com a dele apontada para você.',
   ftot: 'Os dois sacaram. Só o outro acertou.' },
  arremesso: { n: 'Arremesso', a: 'Destreza', p: 'Atletismo', dano: true, fisico: true,
   d: 'Faca, granada, pedra, o que estiver na mão. O defensor usa Destreza + Atletismo.',
   dez: 'Acertou exatamente onde importava. Se for explosivo, pegou mais de um alvo.',
   col: 'O objeto foi para o lugar errado — e ainda vai fazer efeito lá.',
   ftot: 'Você se desfez do objeto sem nenhum resultado.' },
  agarrao: { n: 'Agarrão', a: 'Força', p: 'Briga', fisico: true,
   d: 'Força + Briga contra Força + Briga. Vencendo, você não causa dano: imobiliza. O alvo não se desloca nem ataca terceiros.',
   dez: 'Imobilização total. No próximo turno você escolhe: ferir com a margem cheia, prender de vez ou usá-lo como escudo.',
   col: 'Você agarrou e ficou preso junto. Os dois estão no chão, e mais alguém está chegando.',
   ftot: 'Ele escorregou. Você está de braços abertos na frente dele.' },
  quirk: { n: 'Ataque com poder', trilha: true, dano: true,
   d: 'Parada conforme o poder. Ativar custa Força de Vontade: nível 1 grátis · 2 e 3, 1 superficial · 4, 2 superficiais · 5, 1 agravado e uma vez por cena. Com a Vontade cheia de dano, nada ativa.',
   dez: 'O poder sai maior do que você pediu. O efeito atinge a cena inteira, e alguém que não devia ver, viu.',
   col: 'O poder disparou errado. Se você é Punk, é o Devil\'s Blood: o que estiver mais perto sofre 2 de dano superficial — ou você, se não houver ninguém.',
   ftot: 'Você gastou a Vontade e não saiu nada.' }
 }},
 defesa: { rot: 'Defesa', tipos: {
  apararbriga: { n: 'Aparar desarmado', a: 'Destreza', p: 'Briga', fisico: true, contra: true,
   d: 'Vencendo, você também causa dano: a defesa vira contra-ataque na mesma rolagem. Desarmado, esse dano é superficial.',
   dez: 'Você não só aparou: desarmou, derrubou ou imobilizou. O adversário perde a ação do próximo turno.',
   col: 'A guarda cedeu. Além do dano, você fica com −1 dado nas defesas do próximo turno.',
   ftot: 'Você não chegou a levantar o braço.' },
  aparararma: { n: 'Aparar com arma', a: 'Destreza', p: 'Armamento', fisico: true, contra: true,
   d: 'Vencendo, você também causa dano com a sua arma. É a melhor defesa quando você está armado.',
   dez: 'Aparou e devolveu no mesmo movimento. A arma do adversário voa, quebra ou fica presa na sua.',
   col: 'O impacto foi absorvido pela arma, não por você — e ela não aguentou.',
   ftot: 'Você aparou o ar.' },
  esquiva: { n: 'Esquivar', a: 'Destreza', p: 'Atletismo', fisico: true,
   d: 'Funciona contra qualquer coisa, inclusive o que não daria para aparar. Mas você não causa dano nenhum, por maior que seja a margem.',
   dez: 'Você saiu antes do golpe chegar e terminou em posição melhor. O seu próximo ataque ganha +2 dados.',
   col: 'Você desviou do golpe e entrou em outro problema: escorregou, ficou sem cobertura, entrou na linha de tiro de alguém.',
   ftot: 'Você se moveu na direção do golpe.' },
  defesatiro: { n: 'Defesa contra disparo', a: 'Destreza', p: 'Atletismo', fisico: true,
   d: 'Destreza + Atletismo. Cobertura, a critério do Narrador, pode somar dados à defesa.',
   dez: 'Você leu o disparo antes de ele sair. O tiro acertou onde você estava, e quem atirou perde a próxima ação se reposicionando.',
   col: 'Você foi para o lugar errado. Perdeu a cobertura, e todo mundo viu para onde você foi.',
   ftot: 'Você ficou parado em campo aberto.' },
  defesaquirk: { n: 'Defesa com poder', trilha: true,
   d: 'Parada conforme o poder. Ativar custa Força de Vontade como qualquer ativação.',
   dez: 'A proteção se estende a todos os aliados na cena, sem custo adicional.',
   col: 'O poder falhou no momento exato. Se você é Punk, o Devil\'s Blood dispara.',
   ftot: 'Gastou Vontade e apanhou do mesmo jeito.' },
  defesatotal: { n: 'Defesa total', a: 'Destreza', p: 'Atletismo', fisico: true, bonus: 1,
   d: 'Manobra: +1 dado em todas as defesas do turno, e nenhuma outra ação.',
   dez: 'Ninguém encosta em você, e a sua imobilidade abriu a guarda de alguém: um aliado ganha +2 dados no ataque dele neste turno.',
   col: 'Você se fechou no lugar errado e agora está preso ali.',
   ftot: 'Recuar não era opção, e você recuou.' }
 }},
 pericia: { rot: 'Perícia', tipos: {
  furtividade: { n: 'Furtividade / emboscada', a: 'Destreza', p: 'Furtividade', fisico: true,
   d: 'Contra Raciocínio + Percepção de quem vigia. Vencendo, cabe a manobra Surpresa: ataque contra dificuldade 1, sem defesa, dano dobrado.',
   dez: 'Ninguém viu, ninguém ouviu, e você chegou mais perto do que pretendia.',
   col: 'Alguma coisa fez barulho. Eles ainda não sabem onde você está, mas sabem que há alguém.',
   ftot: 'Você foi visto antes de começar.' },
  percepcao: { n: 'Perceber perigo ou emboscada', a: 'Raciocínio', p: 'Percepção', mental: true,
   d: 'Reflexo. Falhar contra uma emboscada é ser pego de surpresa.',
   dez: 'Você viu tudo: quantos são, onde estão, quem manda. O grupo inteiro age normalmente.',
   col: 'Você percebeu tarde demais, no lugar errado — e avisou em voz alta, entregando que percebeu.',
   ftot: 'Você não viu nada.' },
  investigacao: { n: 'Investigar', a: 'Inteligência', p: 'Investigação', mental: true,
   d: 'Juntar pistas, cruzar registros, reconstruir o que aconteceu. Quase sempre prolongado.',
   dez: 'Você achou o que procurava e mais uma coisa que ninguém sabia que estava ali.',
   col: 'Você achou, e alguém percebeu que você estava procurando.',
   ftot: 'A pista esfriou — e você apagou a próxima sem querer.' },
  medicina: { n: 'Medicina / tratar ferimentos', a: 'Inteligência', p: 'Medicina', mental: true,
   d: 'Com equipamento comum, estabiliza: o agravado para de piorar e passa a contar como superficial para efeito de penalidade. Com equipamento Magitek, remove agravados iguais à metade da Medicina. Uma cena de tratamento.',
   dez: 'Você fez mais do que estancar. O paciente age sem penalidade até o fim da cena.',
   col: 'Você estabilizou e piorou outra coisa. O paciente perde mais um ponto de Saúde antes de melhorar.',
   ftot: 'Você não conseguiu parar o sangramento.' },
  informatica: { n: 'Invadir sistemas', a: 'Inteligência', p: 'Informática', mental: true,
   d: 'Informática cobre hacking, IAs e sistemas Magitek. Sistemas Magitek exigem equipamento compatível.',
   dez: 'Você entrou e deixou uma porta aberta para voltar depois, sem registro nenhum.',
   col: 'Você entrou e o sistema registrou. Alguém, em algum lugar, recebeu um alerta com hora e origem.',
   ftot: 'Acesso negado, e o rastro ficou.' },
  oficios: { n: 'Consertar ou improvisar', a: 'Destreza', p: 'Ofícios', fisico: true,
   d: 'Ofícios cobre implantes, manutenção de Mechas e improvisação de campo. Quase sempre prolongado.',
   dez: 'Ficou melhor do que era, ou levou metade do tempo.',
   col: 'Funcionou, mas vai falhar depois — e você não sabe quando.',
   ftot: 'Quebrou de vez nas suas mãos.' },
  livre: { n: 'Teste livre', livre: true,
   d: 'Escolha o Atributo e a Perícia que o Narrador pedir. Dificuldade: 1 trivial · 2 padrão · 3 difícil · 4 muito difícil · 5 quase impossível.',
   dez: 'Sucesso absoluto. Além do que você pediu, você obtém uma informação, um recurso ou uma posição que não estava no pedido.',
   col: 'Conseguiu, mas custou. O Narrador escolhe o que ficou para trás.',
   ftot: 'Não deu, e a situação piorou.' }
 }},
 social: { rot: 'Social', tipos: {
  persuadir: { n: 'Persuadir', a: 'Manipulação', p: 'Persuasão', social: true,
   d: 'Convencer quem pode dizer não. Contra alguém decidido, é teste disputado.',
   dez: 'Você não venceu o argumento: mudou a sala. Quem ouvia passa a agir conforme o que você disse.',
   col: 'Você disse mais do que devia. Uma verdade sua vazou para quem estava ouvindo.',
   ftot: 'Ninguém acreditou, e agora sabem que você tentou.' },
  intimidar: { n: 'Intimidar', a: 'Presença', p: 'Intimidação', social: true,
   d: 'Contra Perseverança + Autocontrole do alvo.',
   dez: 'O alvo cede por completo e passa a evitar você.',
   col: 'Você assustou a pessoa errada, ou demais: agora ela vai fazer alguma coisa desesperada.',
   ftot: 'Riram de você.' },
  astucia: { n: 'Mentir ou ler a situação', a: 'Manipulação', p: 'Astúcia', social: true,
   d: 'Contra Autocontrole + Empatia de quem ouve.',
   dez: 'Não só acreditaram: repetem a sua versão para outros como se fosse deles.',
   col: 'Alguém na sala não engoliu, e não disse nada.',
   ftot: 'A mentira não parou de pé.' },
  lideranca: { n: 'Comandar sob pressão', a: 'Presença', p: 'Liderança', social: true,
   d: 'Reorganizar aliados em combate, segurar uma linha, impedir uma debandada.',
   dez: 'Cada aliado na cena recupera 1 superficial de Força de Vontade e age antes dos adversários no próximo turno.',
   col: 'Alguém desobedeceu na frente dos outros, e a próxima ordem vale menos.',
   ftot: 'Ninguém se moveu.' }
 }},
 especial: { rot: 'Especial', tipos: {
  remorso: { n: 'Teste de Remorso', remorso: true,
   d: 'Fim de sessão, se houver Manchas. A parada é a Moralidade atual menos o número de Manchas. Um sucesso basta: houve remorso e nada muda. Fracasso total: a Moralidade cai 1. Nos dois casos as Manchas somem.',
   dez: 'O remorso é transformador: além de apagar as Manchas, recupere 1 ponto agravado de Força de Vontade.',
   col: 'O Colapso cobra mesmo aqui: 1 superficial de Vontade, e o Narrador escolhe uma consequência grave ligada ao que você fez.',
   ftot: 'Você não sentiu nada. Moralidade −1.' },
  coercao: { n: 'Resistir a ordem ou coerção', a: 'Perseverança', a2: 'Autocontrole', mental: true,
   d: 'Contra ordem imposta ou coerção mental. A Compulsão racial não se resiste com rolagem: recusá-la custa 1 superficial de Vontade e −2 dados na ação, turno a turno.',
   dez: 'Você não só resistiu: quebrou o mecanismo. A mesma ordem não funciona em você de novo nesta cena.',
   col: 'Você resistiu por fora e cedeu por dentro. Obedeça na próxima oportunidade em que ninguém estiver olhando.',
   ftot: 'Você obedece por uma cena inteira, e lembra de tudo depois.' },
  fadiga: { n: 'Resistir a veneno, doença ou privação', a: 'Vigor', a2: 'Perseverança', fisico: true,
   d: 'Contra ambiente extremo, toxinas, exaustão e os Nexus.',
   dez: 'Você aguenta e ainda segura outro. Escolha um aliado: ele não precisa rolar.',
   col: 'Você aguentou, mas alguma coisa cedeu: −1 dado em paradas físicas até o fim da cena.',
   ftot: 'Você não aguentou. Marque o dano por inteiro.' },
  iniciativa: { n: 'Iniciativa', iniciativa: true,
   d: 'Destreza + Autocontrole + 1d10. Não é parada de dados: soma-se o valor fixo a um d10. Empate: corpo a corpo já engajado, depois disparos, depois corpo a corpo iniciado agora, depois o resto.',
   dez: '', col: '', ftot: '' }
 }}
};
